#import "./fragments/ImageFragment.gql"
#import "./fragments/VideoFragment.gql"

query AllPosts{
  allPosts {
    title
    image{
      ...ImageFragment
    }
    video{
      ...VideoFragment
    }
  }
}